NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.ec.nid.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.ec.nid.com-cert.pem
    OrganizationalUnitIdentifier: peer
