version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nid-version-1
hooks:
  BeforeInstall:
    - location: permissions.sh
      runas: root
  ApplicationStart:
    - location: web/startFabric.sh
      timeout: 300
      runas: ec2-user
