version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nid-version-1
hooks:
  ApplicationStart:
    - location: scripts/permissions.sh
      timeout: 300
      runas: root
    - location: scripts/startUp.sh
      timeout: 500
      runas: root