
Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/nid.com/msp

    - &Moha
        Name: MohaMSP
        ID: MohaMSP
        MSPDir: crypto-config/peerOrganizations/moha.nid.com/msp
        AnchorPeers:
            - Host: peer0.moha.nid.com
              Port: 7051

    - &Ec
        Name: EcMSP
        ID: EcMSP
        MSPDir: crypto-config/peerOrganizations/ec.nid.com/msp
        AnchorPeers:
            - Host: peer0.ec.nid.com
              Port: 7051

Capabilities:
    Global: &ChannelCapabilities
        V1_1: true

    Orderer: &OrdererCapabilities
        V1_1: true

    Application: &ApplicationCapabilities
        V1_2: true

Application: &ApplicationDefaults

    Organizations:

Orderer: &OrdererDefaults
    OrdererType: solo

    Addresses:
        - orderer.nid.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:


Profiles:

    TwoOrgsOrdererGenesis:
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            NIDConsortium:
                Organizations:
                    - *Moha
                    - *Ec
    TwoOrgsChannel:
        Consortium: NIDConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Moha
                - *Ec
            Capabilities:
                <<: *ApplicationCapabilities
