# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.4'

volumes:
  peer0.ec.nid.com:
  peer1.ec.nid.com:
  
networks:
  nidnetwork:
    external:
      name: $SWARM_NETWORK
    
services:
  ec-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=$SWARM_NETWORK
      - FABRIC_CA_SERVER_CA_NAME=ca.ec.nid.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ec.nid.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/abe3a62cc34440813f43fd652068b57d039675ec1b2232b078b68e96a9d61367_sk
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/abe3a62cc34440813f43fd652068b57d039675ec1b2232b078b68e96a9d61367_sk  -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/ec.nid.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ec-ca
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $EC_HOSTNAME

    ports:
     - published: 7054
       target: 7054
       mode: host
    networks:
      nidnetwork:
        aliases:
          - ca.ec.nid.com

  ec-peer0:
    container_name: ec-peer0
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      # folder name + network defined in docker-compose.yaml
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=$SWARM_NETWORK
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      #- CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ID=peer0.ec.nid.com
      - CORE_PEER_ADDRESS=peer0.ec.nid.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.ec.nid.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ec.nid.com:7051
      - CORE_PEER_LOCALMSPID=ecMSP

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

    volumes:
        - /var/run/:/var/run/
        - ../crypto-config/peerOrganizations/ec.nid.com/peers/peer0.ec.nid.com/msp:/etc/hyperledger/fabric/msp
        #- ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/ca:/etc/hyperledger/fabric/ca
        - peer0.ec.nid.com:/var/hyperledger/production
    
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $EC_HOSTNAME

    ports:
            - published: 7051
              target: 7051
              mode: host
            - published: 7053
              target: 7053
              mode: host
    networks:
      nidnetwork:
        aliases:
          - peer0.ec.nid.com
           

  ec-peer1:
    container_name: ec-peer1
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      # folder name + network defined in docker-compose.yaml
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=$SWARM_NETWORK
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      #- CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ID=peer1.ec.nid.com
      - CORE_PEER_ADDRESS=peer1.ec.nid.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ec.nid.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.ec.nid.com:7051
      - CORE_PEER_LOCALMSPID=ecMSP

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

    volumes:
        - /var/run/:/var/run/
        - ../crypto-config/peerOrganizations/ec.nid.com/peers/peer1.ec.nid.com/msp:/etc/hyperledger/fabric/msp
        #- ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/ca:/etc/hyperledger/fabric/ca
        - peer1.ec.nid.com:/var/hyperledger/production
    
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $EC_HOSTNAME

    ports:
            - published: 8051
              target: 7051
              mode: host
            - published: 8053
              target: 7053
              mode: host
    networks:
      nidnetwork:
        aliases:
          - peer1.ec.nid.com

  ec-cli:
    container_name: ec-cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $EC_HOSTNAME

    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=$SWARM_NETWORK
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:////var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.ec.nid.com:7051
      - CORE_PEER_LOCALMSPID=ecMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/crypto/peerOrganizations/ec.nid.com/users/Admin@ec.nid.com/msp

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ../chaincode/:/opt/gopath/src/github.com/chaincode
        - ../crypto-config/:/opt/gopath/src/github.com/hyperledger/fabric/crypto/
        - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/channel-artifacts
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    networks:
      - nidnetwork
