# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.2'

volumes:
  orderer.nid.com:
  peer0.moha.nid.com:
  peer1.moha.nid.com:
  
networks:
  nidnetwork:
    external:
      name: $SWARM_NETWORK
    
services:
  orderer:
    container_name: orderer
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=$SWARM_NETWORK
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/channel-artifacts/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../channel-artifacts:/var/hyperledger/orderer/channel-artifacts
      - ../crypto-config/ordererOrganizations/nid.com/orderers/orderer.nid.com/msp:/var/hyperledger/orderer/msp
      - orderer.nid.com:/var/hyperledger/production/orderer
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $MOHA_HOSTNAME 

    ports:
      - published: 7050
        target: 7050
        mode: host
    networks:
      nidnetwork:
        aliases:
          - orderer.nid.com

  moha-ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=$SWARM_NETWORK
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.moha.nid.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.moha.nid.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/3546ee08d5017e28b29cb84fb6a0c1c99fa93cc3ba58d568f5cbcdf3daf303ee_sk
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.moha.nid.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/3546ee08d5017e28b29cb84fb6a0c1c99fa93cc3ba58d568f5cbcdf3daf303ee_sk  -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/moha.nid.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: moha-ca
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $MOHA_HOSTNAME

    ports:
     - published: 7054
       target: 7054
       mode: host
    networks:
      nidnetwork:
        aliases:
          - ca.moha.nid.com

  moha-peer0:
    container_name: moha-peer0
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      # folder name + network defined in docker-compose.yaml
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=$SWARM_NETWORK
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      #- CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ID=peer0.moha.nid.com
      - CORE_PEER_ADDRESS=peer0.moha.nid.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.moha.nid.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.moha.nid.com:7051
      - CORE_PEER_LOCALMSPID=mohaMSP

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

    volumes:
        - /var/run/:/var/run/
        - ../crypto-config/peerOrganizations/moha.nid.com/peers/peer0.moha.nid.com/msp:/etc/hyperledger/fabric/msp
        #- ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/ca:/etc/hyperledger/fabric/ca
        - peer0.moha.nid.com:/var/hyperledger/production
    
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $MOHA_HOSTNAME

    ports:
            - published: 7051
              target: 7051
              mode: host
            - published: 7053
              target: 7053
              mode: host
    networks:
      nidnetwork:
        aliases:
          - peer0.moha.nid.com
           

  moha-peer1:
    container_name: moha-peer1
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      # folder name + network defined in docker-compose.yaml
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=$SWARM_NETWORK
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      #- CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ID=peer1.moha.nid.com
      - CORE_PEER_ADDRESS=peer1.moha.nid.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.moha.nid.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.moha.nid.com:7051
      - CORE_PEER_LOCALMSPID=mohaMSP

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

    volumes:
        - /var/run/:/var/run/
        - ../crypto-config/peerOrganizations/moha.nid.com/peers/peer1.moha.nid.com/msp:/etc/hyperledger/fabric/msp
        #- ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/ca:/etc/hyperledger/fabric/ca
        - peer1.moha.nid.com:/var/hyperledger/production
    
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $MOHA_HOSTNAME

    ports:
            - published: 8051
              target: 7051
              mode: host
            - published: 8053
              target: 7053
              mode: host
    networks:
      nidnetwork:
        aliases:
          - peer1.moha.nid.com

  moha-cli:
    container_name: moha-cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $MOHA_HOSTNAME

    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=$SWARM_NETWORK
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:////var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.moha.nid.com:7051
      - CORE_PEER_LOCALMSPID=mohaMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/crypto/peerOrganizations/moha.nid.com/users/Admin@moha.nid.com/msp

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ../chaincode/:/opt/gopath/src/github.com/chaincode
        - ../crypto-config/:/opt/gopath/src/github.com/hyperledger/fabric/crypto/
        - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/channel-artifacts
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    networks:
      - nidnetwork