version: '2'

services:

  orderer.nid.com:
    container_name: orderer.nid.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/channel-artifacts/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../channel-artifacts:/var/hyperledger/orderer/channel-artifacts
      - ../crypto-config/ordererOrganizations/nid.com/orderers/orderer.nid.com/msp:/var/hyperledger/orderer/msp
      - orderer.nid.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.moha.nid.com:
    container_name: peer0.moha.nid.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.moha.nid.com
      - CORE_PEER_ADDRESS=peer0.moha.nid.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.moha.nid.com:7051
      - CORE_PEER_LOCALMSPID=mohaMSP
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../crypto-config/peerOrganizations/moha.nid.com/peers/peer0.moha.nid.com/msp:/etc/hyperledger/fabric/msp
      - peer0.moha.nid.com:/var/hyperledger/production
    
    ports:
      - 7051:7051
      - 7053:7053
  
  peer1.moha.nid.com:
    container_name: peer1.moha.nid.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.moha.nid.com
      - CORE_PEER_ADDRESS=peer1.moha.nid.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.moha.nid.com:7051
      - CORE_PEER_LOCALMSPID=mohaMSP
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../crypto-config/peerOrganizations/moha.nid.com/peers/peer1.moha.nid.com/msp:/etc/hyperledger/fabric/msp
      - peer1.moha.nid.com:/var/hyperledger/production
    
    ports:
      - 8051:7051
      - 8053:7053
  
  peer0.ec.nid.com:
    container_name: peer0.ec.nid.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.ec.nid.com
      - CORE_PEER_ADDRESS=peer0.ec.nid.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.ec.nid.com:7051
      - CORE_PEER_LOCALMSPID=ecMSP
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../crypto-config/peerOrganizations/ec.nid.com/peers/peer0.ec.nid.com/msp:/etc/hyperledger/fabric/msp
      - peer0.ec.nid.com:/var/hyperledger/production
    
    ports:
      - 9051:7051
      - 9053:7053
  
  peer1.ec.nid.com:
    container_name: peer1.ec.nid.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.ec.nid.com
      - CORE_PEER_ADDRESS=peer1.ec.nid.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ec.nid.com:7051
      - CORE_PEER_LOCALMSPID=ecMSP
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../crypto-config/peerOrganizations/ec.nid.com/peers/peer1.ec.nid.com/msp:/etc/hyperledger/fabric/msp
      - peer1.ec.nid.com:/var/hyperledger/production
    
    ports:
      - 10051:7051
      - 10053:7053