# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.nid.com:
  peer0.moha.nid.com:
  peer1.moha.nid.com:
  peer0.ec.nid.com:
  peer1.ec.nid.com:
  couchdbmoha0:
  couchdbmoha1:
  couchdbec0:

networks:
  nidnetwork:

services:

  ca.moha.nid.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.moha.nid.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.moha.nid.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/23c5908043c1be209e564c10b3b734e9f7d507942b5bbc78f64478ce9dc361c5_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.moha.nid.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/23c5908043c1be209e564c10b3b734e9f7d507942b5bbc78f64478ce9dc361c5_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/moha.nid.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.moha.nid.com
    networks:
      - nidnetwork

  ca.ec.nid.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.ec.nid.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ec.nid.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d80f0be34b119c242d9074327e3dc7dcebf6544772331ce83573c34899b9cb1b_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.ec.nid.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/d80f0be34b119c242d9074327e3dc7dcebf6544772331ce83573c34899b9cb1b_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/ec.nid.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.ec.nid.com
    networks:
      - nidnetwork


  orderer.nid.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.nid.com
    container_name: orderer.nid.com
    networks:
      - nidnetwork

  peer0.moha.nid.com:
    container_name: peer0.moha.nid.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.moha.nid.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbmoha0:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    networks:
      - nidnetwork

  couchdbmoha0:
    container_name: couchdbmoha0
    image: hyperledger/fabric-couchdb:$IMAGE_TAG
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - nidnetwork

  peer1.moha.nid.com:
    container_name: peer1.moha.nid.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.moha.nid.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbmoha1:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    networks:
      - nidnetwork

  couchdbmoha1:
    container_name: couchdbmoha1
    image: hyperledger/fabric-couchdb:$IMAGE_TAG
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:5984
    networks:
      - nidnetwork

  peer0.ec.nid.com:
    container_name: peer0.ec.nid.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.ec.nid.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbec0:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    networks:
      - nidnetwork
  
  couchdbec0:
    container_name: couchdbec0
    image: hyperledger/fabric-couchdb:$IMAGE_TAG
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 7984:5984
    networks:
      - nidnetwork

  peer1.ec.nid.com:
    container_name: peer1.ec.nid.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.ec.nid.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbec1:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    networks:
      - nidnetwork
    
  couchdbec1:
    container_name: couchdbec1
    image: hyperledger/fabric-couchdb:$IMAGE_TAG
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 8984:5984
    networks:
      - nidnetwork

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.moha.nid.com:7051
      - CORE_PEER_LOCALMSPID=MohaMSP
      # - CORE_PEER_TLS_ENABLED=true
      # - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/moha.nid.com/peers/peer0.moha.nid.com/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/moha.nid.com/peers/peer0.moha.nid.com/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/moha.nid.com/peers/peer0.moha.nid.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/moha.nid.com/users/Admin@moha.nid.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.nid.com
      - peer0.moha.nid.com
      - peer1.moha.nid.com
      - peer0.ec.nid.com
      - peer1.ec.nid.com
    networks:
      - nidnetwork
